# Generated by Django 3.1.2 on 2020-10-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emailtb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.TextField(blank=True, max_length=30, null=True)),
                ('Lastname', models.TextField(blank=True, max_length=30, null=True)),
                ('Emailid', models.EmailField(blank=True, max_length=30, null=True)),
                ('Mobilenumber', models.IntegerField(blank=True, null=True)),
                ('Addrs', models.TextField(blank=True, max_length=30, null=True)),
                ('Place', models.TextField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
